name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 1-reverse-lookup # 或者你的主要分支名稱，例如 main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20 # 依據專案需求，一般 20 即可

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # vue 編譯出來的資料夾名稱，若專案設定不同請調整

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
